spring:
  main:
    allow-circular-references: true
  datasource:
    username: ${dbUser:root}
    url: jdbc:mysql://localhost/lista?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: ${dbPassword:Gestao-Financeira@}
  flyway:
    locations: classpath:db/migration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'